'use client';

import Link from 'next/link';
import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowLeft, CheckCircle2, ExternalLink, PackageCheck, RefreshCw, Save, Settings2, ShieldAlert, Store, Truck } from 'lucide-react';
import { getFreshSessionToken, isMasterUser } from '@/lib/firebase';
import { KOREAN_STUFF_CATEGORIES, type KoreanStuffCategory, type KoreanStuffOrder, type KoreanStuffProduct, type KoreanStuffSettings, type KoreanStuffSupplier } from '@/lib/koreanStuff';
import { useGlobalStore } from '@/store/useGlobalStore';

type Tab = 'overview' | 'products' | 'suppliers' | 'orders' | 'rules';
type ProductDraft = { id?: string; title: string; category: KoreanStuffCategory | ''; brand: string; sourceUrl: string; sourceName: string; supplierId: string; supplierName: string; sourcePrice: string; averagePrice: string; stock: string; shippingDays: string; images: string; shipsTo: string; status: KoreanStuffProduct['status'] };
type SupplierDraft = { id?: string; name: string; sourceUrl: string; feedUrl: string; country: string; shippingDays: string; defaultCategory: KoreanStuffCategory | ''; status: KoreanStuffSupplier['status'] };

const blankProduct: ProductDraft = { title: '', category: '', brand: '', sourceUrl: '', sourceName: '', supplierId: '', supplierName: '', sourcePrice: '', averagePrice: '', stock: '', shippingDays: '3', images: '', shipsTo: '', status: 'REVIEW' };
const blankSupplier: SupplierDraft = { name: '', sourceUrl: '', feedUrl: '', country: '', shippingDays: '3', defaultCategory: '', status: 'REVIEW' };
const defaultSettings: KoreanStuffSettings = { markupRate: .25, maxPriceVariance: 30, maxShippingDays: 3, autoPublishApproved: false, updatedAt: '', updatedBy: '' };

function money(value: number) { return `$${Number(value || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }

export default function KoreanStuffMaster() {
  const user = useGlobalStore((state) => state.user);
  const [tab, setTab] = useState<Tab>('overview');
  const [products, setProducts] = useState<KoreanStuffProduct[]>([]);
  const [suppliers, setSuppliers] = useState<KoreanStuffSupplier[]>([]);
  const [orders, setOrders] = useState<KoreanStuffOrder[]>([]);
  const [settings, setSettings] = useState<KoreanStuffSettings>(defaultSettings);
  const [product, setProduct] = useState<ProductDraft>(blankProduct);
  const [supplier, setSupplier] = useState<SupplierDraft>(blankSupplier);
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const load = async () => {
    const token = await getFreshSessionToken();
    if (!token || !isMasterUser(user)) { setLoading(false); return; }
    setLoading(true);
    try {
      const response = await fetch('/api/master/korean-stuff', { cache: 'no-store', headers: { authorization: `Bearer ${token}` } });
      const payload = await response.json() as { products?: KoreanStuffProduct[]; suppliers?: KoreanStuffSupplier[]; orders?: KoreanStuffOrder[]; settings?: KoreanStuffSettings; error?: string };
      if (!response.ok) throw new Error(payload.error || '운영 데이터를 불러오지 못했습니다.');
      setProducts(payload.products || []);
      setSuppliers(payload.suppliers || []);
      setOrders(payload.orders || []);
      setSettings({ ...defaultSettings, ...(payload.settings || {}) });
    } catch (error) {
      setMessage(error instanceof Error ? error.message : '운영 데이터를 불러오지 못했습니다.');
    } finally { setLoading(false); }
  };

  useEffect(() => { void load(); }, [user?.id]);

  const post = async (body: Record<string, unknown>) => {
    const token = await getFreshSessionToken();
    if (!token) throw new Error('마스터 로그인 세션이 없습니다.');
    const response = await fetch('/api/master/korean-stuff', { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${token}` }, body: JSON.stringify(body) });
    const payload = await response.json() as { error?: string; message?: string };
    if (!response.ok) throw new Error(payload.error || '운영 데이터를 저장하지 못했습니다.');
    setMessage(payload.message || '운영 데이터가 저장되었습니다.');
    await load();
  };

  const saveProduct = async (event: FormEvent) => {
    event.preventDefault(); setSaving(true);
    try {
      await post({ action: 'saveProduct', product: { ...product, sourcePrice: Number(product.sourcePrice), averagePrice: product.averagePrice ? Number(product.averagePrice) : undefined, stock: Number(product.stock), shippingDays: Number(product.shippingDays), images: product.images.split('\n').map((value) => value.trim()).filter(Boolean), shipsTo: product.shipsTo.split('\n').map((value) => value.trim()).filter(Boolean), markupRate: settings.markupRate } });
      setProduct(blankProduct);
    } catch (error) { setMessage(error instanceof Error ? error.message : '상품 저장 실패'); } finally { setSaving(false); }
  };

  const saveSupplier = async (event: FormEvent) => {
    event.preventDefault(); setSaving(true);
    try { await post({ action: 'saveSupplier', supplier: { ...supplier, shippingDays: Number(supplier.shippingDays) } }); setSupplier(blankSupplier); }
    catch (error) { setMessage(error instanceof Error ? error.message : '공급원 저장 실패'); } finally { setSaving(false); }
  };

  const syncSupplier = async (supplierId: string) => { setSaving(true); try { await post({ action: 'syncSupplier', supplierId }); } catch (error) { setMessage(error instanceof Error ? error.message : '공급원 동기화 실패'); } finally { setSaving(false); } };
  const saveRules = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await post({ action: 'saveSettings', settings }); } catch (error) { setMessage(error instanceof Error ? error.message : '정책 저장 실패'); } finally { setSaving(false); } };
  const updateOrder = async (order: KoreanStuffOrder, patch: Partial<KoreanStuffOrder>) => { setSaving(true); try { await post({ action: 'updateOrder', order: { ...order, ...patch } }); } catch (error) { setMessage(error instanceof Error ? error.message : '주문 저장 실패'); } finally { setSaving(false); } };

  if (!isMasterUser(user)) return <div className="mx-auto max-w-xl px-4 py-24 text-center text-slate-200"><ShieldAlert className="mx-auto mb-4 text-rose-400" size={42} /><h1 className="text-2xl font-black">마스터 전용 운영센터</h1><p className="mt-3 text-sm text-slate-500">관리자 계정으로 로그인해야 접근할 수 있습니다.</p></div>;

  const tabs: Array<[Tab, string, string]> = [['overview', 'Overview', '운영 현황'], ['products', 'Products', '상품 승인'], ['suppliers', 'Suppliers', '공급원'], ['orders', 'Orders', '주문·배송'], ['rules', 'Rules', '정책·자동화']];
  return <div className="mx-auto max-w-[1500px] px-4 py-8 text-slate-100 sm:px-6">
    <header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><Link href="/master" className="mb-4 inline-flex items-center gap-2 text-xs font-bold text-slate-500 hover:text-white"><ArrowLeft size={14} /> 운영자 센터</Link><p className="text-[10px] font-black uppercase tracking-[.25em] text-lime-300">KOREAN STUFF / CONTROL ROOM</p><h1 className="mt-2 text-4xl font-black tracking-tight">운영 가능한 쇼핑 채널</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">실제 공급원 피드, 승인 상품, 주문·배송 상태를 분리해서 관리합니다. 데이터가 없는 영역에는 샘플을 표시하지 않습니다.</p></div><div className="flex items-center gap-2"><Link href="/korean-stuff" target="_blank" className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs font-bold text-slate-300"><ExternalLink size={14} /> 스토어 보기</Link><button type="button" onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl bg-lime-300 px-3 py-2 text-xs font-black text-slate-950"><RefreshCw size={14} /> 새로고침</button></div></header>
    <nav className="mb-6 grid grid-cols-2 gap-2 rounded-2xl border border-white/10 bg-white/[.025] p-2 sm:grid-cols-5" aria-label="Korean Stuff 운영 탭">{tabs.map(([id, label, description]) => <button key={id} type="button" onClick={() => setTab(id)} className={`rounded-xl px-3 py-3 text-left transition ${tab === id ? 'bg-lime-300 text-slate-950' : 'text-slate-400 hover:bg-white/10 hover:text-white'}`}><span className="block text-xs font-black">{label}</span><span className={`mt-1 block text-[10px] ${tab === id ? 'text-slate-700' : 'text-slate-500'}`}>{description}</span></button>)}</nav>
    {message && <div className="mb-5 flex items-center justify-between gap-3 rounded-xl border border-lime-300/20 bg-lime-300/10 px-4 py-3 text-sm text-lime-100"><span>{message}</span><button type="button" onClick={() => setMessage('')} aria-label="메시지 닫기">×</button></div>}
    {loading ? <div className="rounded-2xl border border-white/10 p-10 text-center text-sm text-slate-500">실제 운영 데이터를 확인하는 중입니다.</div> : <>
      {tab === 'overview' && <section className="grid gap-4 md:grid-cols-4"><Metric icon={<PackageCheck size={18} />} label="승인 상품" value={products.filter((item) => item.status === 'APPROVED').length} detail="스토어 노출 가능" /><Metric icon={<Store size={18} />} label="등록 공급원" value={suppliers.length} detail="실제 연결된 운영 데이터" /><Metric icon={<Truck size={18} />} label="처리 중 주문" value={orders.filter((item) => !['DELIVERED', 'CANCELLED'].includes(item.status)).length} detail="주문·배송 탭에서 처리" /><Metric icon={<Settings2 size={18} />} label="자동 승인" value={settings.autoPublishApproved ? 'ON' : 'OFF'} detail={`${Math.round(settings.markupRate * 100)}% markup · ${settings.maxShippingDays}일`} /><div className="md:col-span-4 rounded-2xl border border-white/10 bg-white/[.025] p-6"><h2 className="text-lg font-black">운영 체크</h2><div className="mt-4 grid gap-3 text-sm text-slate-400 sm:grid-cols-3"><CheckLine ok={suppliers.length > 0} text="공급원 등록" /><CheckLine ok={products.some((item) => item.status === 'APPROVED')} text="승인 상품 공개" /><CheckLine ok={orders.length > 0} text="주문 원장 연결" /></div></div></section>}
      {tab === 'products' && <section className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_420px]"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><SectionTitle title="상품 승인 대기열" description="실제 공급원 정보와 검증된 배송 조건이 없는 상품은 승인할 수 없습니다." />{products.length === 0 ? <Empty text="등록된 상품이 없습니다." /> : <div className="space-y-3">{products.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 py-4 last:border-0"><div className="flex min-w-0 items-center gap-3"><div className="h-14 w-12 overflow-hidden bg-white/10">{item.images[0] && <img src={item.images[0]} alt="" className="h-full w-full object-cover" />}</div><div className="min-w-0"><p className="truncate font-bold">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.supplierName} · {money(item.salePrice)} · 재고 {item.stock}</p><p className="mt-1 text-[10px] text-slate-500">{item.status} · {item.shippingDays}일 · 평균가 차이 {item.priceVariance ?? '-'}%</p></div></div><div className="flex items-center gap-2"><span className="rounded-full border border-white/10 px-2 py-1 text-[10px] text-slate-400">{item.category}</span><button type="button" onClick={() => setProduct({ id: item.id, title: item.title, category: item.category, brand: item.brand || '', sourceUrl: item.sourceUrl, sourceName: item.sourceName, supplierId: item.supplierId, supplierName: item.supplierName, sourcePrice: String(item.sourcePrice), averagePrice: item.averagePrice ? String(item.averagePrice) : '', stock: String(item.stock), shippingDays: String(item.shippingDays), images: item.images.join('\n'), shipsTo: item.shipsTo.join('\n'), status: item.status })} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-bold">편집</button></div></div>)}</div>}</div><ProductForm value={product} setValue={setProduct} onSubmit={saveProduct} saving={saving} /></section>}
      {tab === 'suppliers' && <section className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_420px]"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><SectionTitle title="공급원 연결" description="HTTPS JSON 피드를 연결하면 실제 상품을 읽어 검토 대기열에 넣습니다. 임의의 상품을 생성하지 않습니다." />{suppliers.length === 0 ? <Empty text="등록된 공급원이 없습니다." /> : <div className="space-y-3">{suppliers.map((item) => <div key={item.id} className="border-b border-white/10 py-4 last:border-0"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{item.name}</p><p className="mt-1 text-xs text-slate-500">{item.country} · {item.shippingDays}일 · {item.status}</p></div><div className="flex gap-2"><button type="button" onClick={() => setSupplier({ id: item.id, name: item.name, sourceUrl: item.sourceUrl, feedUrl: item.feedUrl || '', country: item.country, shippingDays: String(item.shippingDays), defaultCategory: item.defaultCategory || '', status: item.status })} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-bold">편집</button><button type="button" disabled={!item.feedUrl || saving} onClick={() => void syncSupplier(item.id)} className="inline-flex items-center gap-1 rounded-lg bg-cyan-300 px-3 py-2 text-xs font-black text-slate-950 disabled:opacity-40"><RefreshCw size={12} /> 피드 동기화</button></div></div><p className="mt-2 text-[10px] text-slate-500">{item.lastSyncAt ? `${item.lastSyncAt} · ${item.lastSyncMessage || item.lastSyncStatus}` : '아직 동기화하지 않음'}</p></div>)}</div>}</div><SupplierForm value={supplier} setValue={setSupplier} onSubmit={saveSupplier} saving={saving} /></section>}
      {tab === 'orders' && <OrdersTable orders={orders} saving={saving} onUpdate={updateOrder} />}
      {tab === 'rules' && <RulesForm settings={settings} setSettings={setSettings} onSubmit={saveRules} saving={saving} />}
    </>}
  </div>;
}

function Metric({ icon, label, value, detail }: { icon: ReactNode; label: string; value: string | number; detail: string }) { return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-center gap-2 text-lime-300">{icon}<span className="text-[10px] font-black uppercase tracking-[.16em]">{label}</span></div><p className="mt-5 text-3xl font-black">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div>; }
function CheckLine({ ok, text }: { ok: boolean; text: string }) { return <div className="flex items-center gap-2">{ok ? <CheckCircle2 size={16} className="text-lime-300" /> : <ShieldAlert size={16} className="text-amber-300" />}<span>{text}</span><span className="text-xs text-slate-600">{ok ? '완료' : '대기'}</span></div>; }
function Empty({ text }: { text: string }) { return <div className="flex min-h-48 items-center justify-center text-sm text-slate-500">{text}</div>; }
function SectionTitle({ title, description }: { title: string; description: string }) { return <div className="mb-5"><h2 className="text-lg font-black">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div>; }
function Field({ label, value, onChange, type = 'text', placeholder = '' }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) { return <label className="grid gap-2 text-xs font-bold text-slate-400"><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="rounded-lg border border-white/10 bg-white/[.05] px-3 py-2.5 text-sm font-normal text-white outline-none focus:border-lime-300" /></label>; }
function TextArea({ label, value, onChange, placeholder = '' }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) { return <label className="grid gap-2 text-xs font-bold text-slate-400"><span>{label}</span><textarea rows={3} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="rounded-lg border border-white/10 bg-white/[.05] px-3 py-2.5 text-sm font-normal text-white outline-none focus:border-lime-300" /></label>; }
function CategorySelect({ value, onChange }: { value: KoreanStuffCategory | ''; onChange: (value: KoreanStuffCategory | '') => void }) { return <label className="grid gap-2 text-xs font-bold text-slate-400"><span>카테고리</span><select value={value} onChange={(event) => onChange(event.target.value as KoreanStuffCategory | '')} className="rounded-lg border border-white/10 bg-[#151a22] px-3 py-2.5 text-sm font-normal text-white outline-none"><option value="">선택</option>{KOREAN_STUFF_CATEGORIES.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>; }

function ProductForm({ value, setValue, onSubmit, saving }: { value: ProductDraft; setValue: (value: ProductDraft) => void; onSubmit: (event: FormEvent) => void; saving: boolean }) {
  const update = (key: keyof ProductDraft, next: string) => setValue({ ...value, [key]: next });
  return <form onSubmit={onSubmit} className="rounded-2xl border border-lime-300/20 bg-lime-300/[.04] p-5"><SectionTitle title={value.id ? '상품 편집' : '실제 상품 등록'} description="공급원 URL·이미지·재고·배송일을 입력한 상품만 승인할 수 있습니다." /><div className="grid gap-3 sm:grid-cols-2"><Field label="상품명" value={value.title} onChange={(next) => update('title', next)} /><CategorySelect value={value.category} onChange={(next) => setValue({ ...value, category: next })} /><Field label="브랜드" value={value.brand} onChange={(next) => update('brand', next)} /><Field label="공급원명" value={value.sourceName} onChange={(next) => update('sourceName', next)} /><Field label="공급원 URL" value={value.sourceUrl} onChange={(next) => update('sourceUrl', next)} placeholder="https://" /><Field label="판매자 ID" value={value.supplierId} onChange={(next) => update('supplierId', next)} /><Field label="판매자명" value={value.supplierName} onChange={(next) => update('supplierName', next)} /><Field label="공급가 USD" value={value.sourcePrice} onChange={(next) => update('sourcePrice', next)} type="number" /><Field label="평균가 USD (선택)" value={value.averagePrice} onChange={(next) => update('averagePrice', next)} type="number" /><Field label="재고 수량" value={value.stock} onChange={(next) => update('stock', next)} type="number" /><Field label="배송일" value={value.shippingDays} onChange={(next) => update('shippingDays', next)} type="number" /><label className="grid gap-2 text-xs font-bold text-slate-400"><span>상태</span><select value={value.status} onChange={(event) => setValue({ ...value, status: event.target.value as ProductDraft['status'] })} className="rounded-lg border border-white/10 bg-[#151a22] px-3 py-2.5 text-sm font-normal text-white outline-none"><option value="DRAFT">DRAFT</option><option value="REVIEW">REVIEW</option><option value="APPROVED">APPROVED</option><option value="PAUSED">PAUSED</option><option value="REJECTED">REJECTED</option></select></label><TextArea label="상품 이미지 URL (한 줄씩)" value={value.images} onChange={(next) => update('images', next)} placeholder="https://..." /><TextArea label="배송 권역 (한 줄씩)" value={value.shipsTo} onChange={(next) => update('shipsTo', next)} placeholder="US" /></div><button disabled={saving} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-lime-300 px-4 py-3 text-xs font-black text-slate-950 disabled:opacity-50"><Save size={14} /> 상품 저장</button></form>;
}

function SupplierForm({ value, setValue, onSubmit, saving }: { value: SupplierDraft; setValue: (value: SupplierDraft) => void; onSubmit: (event: FormEvent) => void; saving: boolean }) { const update = (key: keyof SupplierDraft, next: string) => setValue({ ...value, [key]: next }); return <form onSubmit={onSubmit} className="rounded-2xl border border-cyan-300/20 bg-cyan-300/[.04] p-5"><SectionTitle title={value.id ? '공급원 편집' : '공급원 연결'} description="실제 HTTPS JSON 상품 피드만 동기화할 수 있습니다." /><div className="grid gap-3"><Field label="공급원명" value={value.name} onChange={(next) => update('name', next)} /><Field label="공식 홈페이지" value={value.sourceUrl} onChange={(next) => update('sourceUrl', next)} placeholder="https://" /><Field label="JSON 상품 피드" value={value.feedUrl} onChange={(next) => update('feedUrl', next)} placeholder="https://.../products.json" /><Field label="국가·배송 권역" value={value.country} onChange={(next) => update('country', next)} /><Field label="배송일" value={value.shippingDays} onChange={(next) => update('shippingDays', next)} type="number" /><CategorySelect value={value.defaultCategory} onChange={(next) => setValue({ ...value, defaultCategory: next })} /></div><button disabled={saving} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-cyan-300 px-4 py-3 text-xs font-black text-slate-950 disabled:opacity-50"><Save size={14} /> 공급원 저장</button></form>; }

function OrdersTable({ orders, saving, onUpdate }: { orders: KoreanStuffOrder[]; saving: boolean; onUpdate: (order: KoreanStuffOrder, patch: Partial<KoreanStuffOrder>) => void }) { return <section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><SectionTitle title="주문·배송 운영" description="결제된 실제 주문의 공급자 주문번호, 송장번호, 배송 상태를 관리합니다. 환불은 별도 원장 처리 후 진행합니다." />{orders.length === 0 ? <Empty text="주문 원장이 없습니다." /> : <div className="space-y-4">{orders.map((order) => <div key={order.id} className="grid gap-4 border-b border-white/10 pb-4 last:border-0 lg:grid-cols-[minmax(0,1fr)_180px_220px]"><div><p className="font-bold">{order.title}</p><p className="mt-1 text-xs text-slate-500">{order.id} · {order.quantity}개 · {money(order.total)} · 회원 {order.userId}</p><p className="mt-1 text-xs text-slate-400">{order.shippingName} · {order.shippingPostalCode} · {order.shippingAddress}</p></div><select value={order.status} disabled={saving} onChange={(event) => void onUpdate(order, { status: event.target.value as KoreanStuffOrder['status'] })} className="h-10 rounded-lg border border-white/10 bg-[#151a22] px-3 text-xs text-white"><option value="PAID">PAID</option><option value="FULFILLMENT_REVIEW">FULFILLMENT_REVIEW</option><option value="PURCHASED">PURCHASED</option><option value="SHIPPING">SHIPPING</option><option value="IN_TRANSIT">IN_TRANSIT</option><option value="DELIVERED">DELIVERED</option><option value="REFUND_REVIEW">REFUND_REVIEW</option></select><div className="grid gap-2"><input defaultValue={order.trackingNumber || ''} placeholder="송장번호" onBlur={(event) => { if (event.target.value !== (order.trackingNumber || '')) void onUpdate(order, { trackingNumber: event.target.value }); }} className="rounded-lg border border-white/10 bg-white/[.05] px-3 py-2 text-xs text-white outline-none" /><input defaultValue={order.supplierOrderId || ''} placeholder="판매자 주문번호" onBlur={(event) => { if (event.target.value !== (order.supplierOrderId || '')) void onUpdate(order, { supplierOrderId: event.target.value }); }} className="rounded-lg border border-white/10 bg-white/[.05] px-3 py-2 text-xs text-white outline-none" /></div></div>)}</div>}</section>; }

function RulesForm({ settings, setSettings, onSubmit, saving }: { settings: KoreanStuffSettings; setSettings: (value: KoreanStuffSettings) => void; onSubmit: (event: FormEvent) => void; saving: boolean }) { return <form onSubmit={onSubmit} className="max-w-3xl rounded-2xl border border-white/10 bg-white/[.025] p-6"><SectionTitle title="가격·승인·배송 정책" description="상품 자동 승인 기준입니다. 수치는 실제 공급원 데이터에만 적용됩니다." /><div className="grid gap-4 sm:grid-cols-3"><Field label="Markup 비율" value={String(settings.markupRate * 100)} onChange={(value) => setSettings({ ...settings, markupRate: Number(value || 0) / 100 })} type="number" /><Field label="평균가 차이 상한 %" value={String(settings.maxPriceVariance)} onChange={(value) => setSettings({ ...settings, maxPriceVariance: Number(value || 0) })} type="number" /><Field label="최대 배송일 (최대 3일)" value={String(settings.maxShippingDays)} onChange={(value) => setSettings({ ...settings, maxShippingDays: Math.min(3, Number(value || 0)) })} type="number" /></div><label className="mt-6 flex items-center gap-3 text-sm text-slate-300"><input type="checkbox" checked={settings.autoPublishApproved} onChange={(event) => setSettings({ ...settings, autoPublishApproved: event.target.checked })} className="h-4 w-4 accent-lime-300" />검증을 통과한 피드 상품 자동 승인</label><div className="mt-5 rounded-xl border border-amber-300/20 bg-amber-300/[.06] p-4 text-xs leading-5 text-amber-100">자동 승인을 켜도 공급원 URL, 이미지, 재고, 3일 이내 배송, 평균가 차이 조건을 모두 통과하지 못한 상품은 검토 대기로 남습니다.</div><button disabled={saving} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-lime-300 px-4 py-3 text-xs font-black text-slate-950 disabled:opacity-50"><Save size={14} /> 정책 저장</button></form>; }
